const GUILD_UPDATE = "GUILD_UPDATE";
const GUILD_DELETE = "GUILD_DELETE";

const CHANNELS_UPDATE = "CHANNELS_UPDATE";

const MEMBER_ADD = "MEMBER_ADD";
const MEMBER_DELETE = "MEMBER_DELETE";
const MEMBER_TYPING = "MEMBER_TYPING";

const MESSAGE_ADD = "MESSAGE_ADD";

const USER_UPDATE = "USER_UPDATE";

const HELLO = "HELLO";
const PING = "PING";
const PONG = "PONG";

module.exports = {
  GUILD_UPDATE,
  GUILD_DELETE,
  CHANNELS_UPDATE,
  MEMBER_ADD,
  MEMBER_DELETE,
  MEMBER_TYPING,
  MESSAGE_ADD,
  USER_UPDATE,
  HELLO,
  PING,
  PONG
};
